-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 18:48:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`libro` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `isbn` VARCHAR(13) NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `numeroPaginas` INT NULL,
  `fechaPublicacion` DATE NULL,
  `prestadoSiNo` TINYINT NULL,
  `fechaDevolucion` DATE NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`socio` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`socio` (
  `codigoSocio` INT NOT NULL,
  `nombreSocio` VARCHAR(45) NULL,
  `apellidoSocio` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  PRIMARY KEY (`codigoSocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
  `libro_isbn` VARCHAR(13) NOT NULL,
  `codigoSocio` INT NOT NULL,
  PRIMARY KEY (`libro_isbn`, `codigoSocio`),
  INDEX `fk_libro_has_socio_socio1_idx` (`codigoSocio` ASC) VISIBLE,
  INDEX `fk_libro_has_socio_libro_idx` (`libro_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_socio_libro`
    FOREIGN KEY (`libro_isbn`)
    REFERENCES `biblioteca`.`libro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_socio_socio1`
    FOREIGN KEY (`codigoSocio`)
    REFERENCES `biblioteca`.`socio` (`codigoSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
