-- MySQL Script generated by MySQL Workbench
-- Mon Mar  8 17:13:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema examenAD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `examenAD` ;

-- -----------------------------------------------------
-- Schema examenAD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examenAD` DEFAULT CHARACTER SET utf8 ;
USE `examenAD` ;

-- -----------------------------------------------------
-- Table `examenAD`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenAD`.`paciente` ;

CREATE TABLE IF NOT EXISTS `examenAD`.`paciente` (
  `idpaciente` INT NOT NULL,
  `numeroSS` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examenAD`.`colegiado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenAD`.`colegiado` ;

CREATE TABLE IF NOT EXISTS `examenAD`.`colegiado` (
  `idcolegiado` INT NOT NULL,
  `numeroColegiado` INT NULL,
  `especialidad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idcolegiado`, `paciente_idpaciente`),
  INDEX `fk_colegiado_paciente_idx` (`paciente_idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_colegiado_paciente`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `examenAD`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examenAD`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `examenAD`.`cita` ;

CREATE TABLE IF NOT EXISTS `examenAD`.`cita` (
  `idcita` INT NOT NULL,
  `dia` INT NULL,
  `tramo` INT NULL,
  `numeroColegiado` INT NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idcita`, `paciente_idpaciente`),
  INDEX `fk_cita_paciente1_idx` (`paciente_idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_cita_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `examenAD`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
