-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 18:22:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jsontosql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jsontosql` ;

-- -----------------------------------------------------
-- Schema jsontosql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jsontosql` DEFAULT CHARACTER SET utf8 ;
USE `jsontosql` ;

-- -----------------------------------------------------
-- Table `jsontosql`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsontosql`.`Libro` ;

CREATE TABLE IF NOT EXISTS `jsontosql`.`Libro` (
  `id_libro` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `precio` INT NULL,
  `totalpaginas` INT NULL,
  PRIMARY KEY (`id_libro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsontosql`.`Generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsontosql`.`Generos` ;

CREATE TABLE IF NOT EXISTS `jsontosql`.`Generos` (
  `idGeneros` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `Libro_id_libro` INT NOT NULL,
  PRIMARY KEY (`idGeneros`),
  INDEX `fk_Generos_Libro1_idx` (`Libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_Generos_Libro1`
    FOREIGN KEY (`Libro_id_libro`)
    REFERENCES `jsontosql`.`Libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsontosql`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsontosql`.`Autor` ;

CREATE TABLE IF NOT EXISTS `jsontosql`.`Autor` (
  `idAutor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Libro_id_libro` INT NOT NULL,
  PRIMARY KEY (`idAutor`),
  INDEX `fk_Autor_Libro_idx` (`Libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Libro`
    FOREIGN KEY (`Libro_id_libro`)
    REFERENCES `jsontosql`.`Libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
